services:
#    aescarcha_challenge.example:
#        class: Aescarcha\ChallengeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    my_user_provider: 
        class: "Aescarcha\UserBundle\Security\Core\User\FOSUBUserProvider"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookId}]
    aescarcha_user.profile.edit.completed:
        class: Aescarcha\UserBundle\EventListener\ProfileEditCompleteListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }